# Generated by Django 4.1.1 on 2022-10-06 02:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schooling', models.CharField(max_length=30, unique=True, verbose_name='schooling')),
                ('level', models.PositiveIntegerField(verbose_name='level')),
            ],
            options={
                'verbose_name': 'schooling',
                'verbose_name_plural': 'schoolings',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('status', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True, verbose_name='friendly url')),
                ('salary_from', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='salary from')),
                ('salary_to', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='salary to')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('company', models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'company')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='company')),
                ('schooling', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.schooling', verbose_name='schooling')),
            ],
            options={
                'verbose_name': 'job',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('status', models.BooleanField(default=True)),
                ('salary_expectation', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='salary expectation')),
                ('candidate', models.ForeignKey(limit_choices_to={'groups__name': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='job')),
            ],
            options={
                'verbose_name': 'application',
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
