# Generated by Django 4.1.1 on 2022-10-25 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=2,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name='score',
            ),
            preserve_default=False,
        ),
    ]
