# Generated by Django 4.1.1 on 2022-09-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={
                'verbose_name': 'salary',
                'verbose_name_plural': 'salaries',
            },
        ),
        migrations.AlterModelOptions(
            name='schooling',
            options={
                'verbose_name': 'schooling',
                'verbose_name_plural': 'schoolings',
            },
        ),
    ]
