# Generated by Django 4.1.1 on 2022-09-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
