# Generated by Django 4.1.1 on 2022-10-25 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_application_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='score',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name='score',
            ),
        ),
    ]
